/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('./.vitepress/theme/components/Icon.vue')['default']
    TodoList: typeof import('./.vitepress/theme/components/TodoList.vue')['default']
  }
}
